version: '3.7'

services:

  mb-node:
    container_name: mb-node
    command: start:dev               
    volumes:
      - .:/usr/src/app
    build:
      context: .
    ports:
      - "3000:3000"

  mb-node-db:
    container_name: mb-node-db
    image: postgres
    restart: unless-stopped
    volumes:
      - dbvolume:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - 5432:5432

volumes:
  dbvolume:
